/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserById"];
        put: operations["updateUser"];
        post?: never;
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateProjectComplete"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllUsers"];
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/files/upload/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/favorites/{projectId}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["toggleFavorite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCompleteProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProjectStatus"];
        trace?: never;
    };
    "/api/users/username/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserByUsername"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/exists/username/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["existsByUsername"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProjectFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProjectFile"];
        put?: never;
        post?: never;
        delete: operations["deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/files/{fileId}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["viewFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/files/{fileId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProjectById"];
        put?: never;
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/manager/{managerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProjectsByManagerId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/favorites/{projectId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFavoriteStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/favorites/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserFavoriteProjectIds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: date-time */
            createDate?: string;
            /** Format: date-time */
            modifyDate?: string;
            /** Format: int64 */
            id?: number;
            username?: string;
            password?: string;
            email?: string;
        };
        ProjectRequest: {
            title?: string;
            description?: string;
            /** @enum {string} */
            projectField?: "PLANNING" | "DESIGN" | "DEVELOPMENT";
            /** @enum {string} */
            recruitmentType?: "PROJECT_CONTRACT" | "PERSONAL_CONTRACT";
            /** @enum {string} */
            budgetType?: "RANGE_1_100" | "RANGE_100_200" | "RANGE_200_300" | "RANGE_300_500" | "RANGE_500_1000" | "RANGE_1000_2000" | "RANGE_2000_3000" | "RANGE_3000_5000" | "RANGE_5000_OVER" | "OVER_1_EUK" | "NEGOTIABLE";
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** Format: int64 */
            managerId?: number;
            /** @enum {string} */
            partnerType?: "INDIVIDUAL_FREELANCER" | "INDIVIDUAL_OR_TEAM_FREELANCER" | "BUSINESS_TEAM_OR_COMPANY" | "ANY_TYPE" | "ETC";
            /** Format: int64 */
            budgetAmount?: number;
            /** @enum {string} */
            progressStatus?: "IDEA_STAGE" | "CONTENT_ORGANIZED" | "DETAILED_PLAN";
            /** @enum {string} */
            companyLocation?: "SEOUL" | "GYEONGGI" | "INCHEON" | "GANGWON" | "CHUNGNAM" | "DAEJEON" | "CHUNGBUK" | "SEJONG" | "BUSAN" | "ULSAN" | "DAEGU" | "GYEONGBUK" | "GYEONGNAM" | "JEONNAM" | "GWANGJU" | "JEONBUK" | "JEJU" | "OVERSEAS";
            partnerEtcDescription?: string;
            techNames?: string[];
            attachmentFileIds?: number[];
            filesToDelete?: number[];
        };
        ApiResponseProjectResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ProjectResponse"];
            error?: string;
        };
        ProjectFileInfo: {
            /** Format: int64 */
            id?: number;
            originalName?: string;
            /** Format: int64 */
            fileSize?: number;
            fileType?: string;
            /** Format: date-time */
            uploadDate?: string;
        };
        ProjectResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            /** @enum {string} */
            projectField?: "PLANNING" | "DESIGN" | "DEVELOPMENT";
            /** @enum {string} */
            recruitmentType?: "PROJECT_CONTRACT" | "PERSONAL_CONTRACT";
            /** @enum {string} */
            budgetType?: "RANGE_1_100" | "RANGE_100_200" | "RANGE_200_300" | "RANGE_300_500" | "RANGE_500_1000" | "RANGE_1000_2000" | "RANGE_2000_3000" | "RANGE_3000_5000" | "RANGE_5000_OVER" | "OVER_1_EUK" | "NEGOTIABLE";
            /** Format: int64 */
            budgetAmount?: number;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** @enum {string} */
            partnerType?: "INDIVIDUAL_FREELANCER" | "INDIVIDUAL_OR_TEAM_FREELANCER" | "BUSINESS_TEAM_OR_COMPANY" | "ANY_TYPE" | "ETC";
            partnerEtcDescription?: string;
            /** @enum {string} */
            progressStatus?: "IDEA_STAGE" | "CONTENT_ORGANIZED" | "DETAILED_PLAN";
            /** @enum {string} */
            companyLocation?: "SEOUL" | "GYEONGGI" | "INCHEON" | "GANGWON" | "CHUNGNAM" | "DAEJEON" | "CHUNGBUK" | "SEJONG" | "BUSAN" | "ULSAN" | "DAEGU" | "GYEONGBUK" | "GYEONGNAM" | "JEONNAM" | "GWANGJU" | "JEONBUK" | "JEJU" | "OVERSEAS";
            /** @enum {string} */
            status?: "RECRUITING" | "CONTRACTING" | "IN_PROGRESS" | "COMPLETED" | "SUSPENDED" | "CANCELLED";
            /** Format: int32 */
            viewCount?: number;
            /** Format: int32 */
            applicantCount?: number;
            /** Format: int64 */
            managerId?: number;
            /** Format: date-time */
            createDate?: string;
            /** Format: date-time */
            modifyDate?: string;
            techStacks?: components["schemas"]["TechInfo"][];
            projectFiles?: components["schemas"]["ProjectFileInfo"][];
        };
        TechInfo: {
            techName?: string;
            /** @enum {string} */
            techCategory?: "FRONTEND" | "BACKEND" | "DATABASE";
        };
        ProjectFile: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            projectId?: number;
            originalName?: string;
            storedName?: string;
            filePath?: string;
            /** Format: int64 */
            fileSize?: number;
            fileType?: string;
            /** Format: date-time */
            uploadDate?: string;
        };
        RsDataProjectFile: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ProjectFile"];
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        RsDataListProjectFile: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ProjectFile"][];
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        RsDataMapStringObject: {
            success?: boolean;
            message?: string;
            data?: {
                [key: string]: unknown;
            };
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ProjectStatusChangeRequest: {
            /** @enum {string} */
            status?: "RECRUITING" | "CONTRACTING" | "IN_PROGRESS" | "COMPLETED" | "SUSPENDED" | "CANCELLED";
            /** Format: int64 */
            changedById?: number;
        };
        ApiResponseProject: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["Project"];
            error?: string;
        };
        Project: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            /** @enum {string} */
            projectField?: "PLANNING" | "DESIGN" | "DEVELOPMENT";
            /** @enum {string} */
            recruitmentType?: "PROJECT_CONTRACT" | "PERSONAL_CONTRACT";
            /** @enum {string} */
            partnerType?: "INDIVIDUAL_FREELANCER" | "INDIVIDUAL_OR_TEAM_FREELANCER" | "BUSINESS_TEAM_OR_COMPANY" | "ANY_TYPE" | "ETC";
            /** @enum {string} */
            budgetType?: "RANGE_1_100" | "RANGE_100_200" | "RANGE_200_300" | "RANGE_300_500" | "RANGE_500_1000" | "RANGE_1000_2000" | "RANGE_2000_3000" | "RANGE_3000_5000" | "RANGE_5000_OVER" | "OVER_1_EUK" | "NEGOTIABLE";
            /** Format: int64 */
            budgetAmount?: number;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** @enum {string} */
            progressStatus?: "IDEA_STAGE" | "CONTENT_ORGANIZED" | "DETAILED_PLAN";
            /** @enum {string} */
            companyLocation?: "SEOUL" | "GYEONGGI" | "INCHEON" | "GANGWON" | "CHUNGNAM" | "DAEJEON" | "CHUNGBUK" | "SEJONG" | "BUSAN" | "ULSAN" | "DAEGU" | "GYEONGBUK" | "GYEONGNAM" | "JEONNAM" | "GWANGJU" | "JEONBUK" | "JEJU" | "OVERSEAS";
            /** @enum {string} */
            status?: "RECRUITING" | "CONTRACTING" | "IN_PROGRESS" | "COMPLETED" | "SUSPENDED" | "CANCELLED";
            /** Format: int32 */
            viewCount?: number;
            /** Format: int32 */
            applicantCount?: number;
            /** Format: int64 */
            managerId?: number;
            /** Format: date-time */
            createDate?: string;
            /** Format: date-time */
            modifyDate?: string;
            partnerEtcDescription?: string;
            projectTechs?: components["schemas"]["ProjectTech"][];
            projectFiles?: components["schemas"]["ProjectFile"][];
            projectFavorites?: components["schemas"]["ProjectFavorite"][];
        };
        ProjectFavorite: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            userId?: number;
            /** Format: int64 */
            projectId?: number;
            /** Format: date-time */
            createDate?: string;
        };
        ProjectTech: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            projectId?: number;
            /** @enum {string} */
            techCategory?: "FRONTEND" | "BACKEND" | "DATABASE";
            techName?: string;
            /** Format: date-time */
            createDate?: string;
        };
        PageProjectResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ProjectResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            unpaged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            paged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        RsDataListLong: {
            success?: boolean;
            message?: string;
            data?: number[];
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        RsDataVoid: {
            success?: boolean;
            message?: string;
            data?: unknown;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: unknown;
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["User"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["User"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProjectComplete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ApiResponseProjectResponse"];
                };
            };
        };
    };
    getAllUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["User"][];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["User"];
                };
            };
        };
    };
    uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataProjectFile"];
                };
            };
        };
    };
    uploadFiles: {
        parameters: {
            query: {
                files: string[];
            };
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataListProjectFile"];
                };
            };
        };
    };
    toggleFavorite: {
        parameters: {
            query: {
                userId: number;
            };
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataMapStringObject"];
                };
            };
        };
    };
    createCompleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ApiResponseProjectResponse"];
                };
            };
        };
    };
    updateProjectStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectStatusChangeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ApiResponseProject"];
                };
            };
        };
    };
    getUserByUsername: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["User"];
                };
            };
        };
    };
    existsByUsername: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": boolean;
                };
            };
        };
    };
    getAllProjects: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                search?: string;
                status?: "RECRUITING" | "CONTRACTING" | "IN_PROGRESS" | "COMPLETED" | "SUSPENDED" | "CANCELLED";
                projectField?: "PLANNING" | "DESIGN" | "DEVELOPMENT";
                recruitmentType?: "PROJECT_CONTRACT" | "PERSONAL_CONTRACT";
                partnerType?: "INDIVIDUAL_FREELANCER" | "INDIVIDUAL_OR_TEAM_FREELANCER" | "BUSINESS_TEAM_OR_COMPANY" | "ANY_TYPE" | "ETC";
                budgetType?: "RANGE_1_100" | "RANGE_100_200" | "RANGE_200_300" | "RANGE_300_500" | "RANGE_500_1000" | "RANGE_1000_2000" | "RANGE_2000_3000" | "RANGE_3000_5000" | "RANGE_5000_OVER" | "OVER_1_EUK" | "NEGOTIABLE";
                minBudget?: number;
                maxBudget?: number;
                location?: string;
                techNames?: string[];
                sortBy?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["PageProjectResponse"];
                };
            };
        };
    };
    getProjectFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ProjectFile"][];
                };
            };
        };
    };
    getProjectFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                fileId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ProjectFile"];
                };
            };
        };
    };
    deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                fileId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    viewFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                fileId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": string;
                };
            };
        };
    };
    downloadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                fileId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": string;
                };
            };
        };
    };
    getProjectById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query: {
                requesterId: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getProjectsByManagerId: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                search?: string;
                status?: "RECRUITING" | "CONTRACTING" | "IN_PROGRESS" | "COMPLETED" | "SUSPENDED" | "CANCELLED";
                projectField?: "PLANNING" | "DESIGN" | "DEVELOPMENT";
                recruitmentType?: "PROJECT_CONTRACT" | "PERSONAL_CONTRACT";
                partnerType?: "INDIVIDUAL_FREELANCER" | "INDIVIDUAL_OR_TEAM_FREELANCER" | "BUSINESS_TEAM_OR_COMPANY" | "ANY_TYPE" | "ETC";
                budgetType?: "RANGE_1_100" | "RANGE_100_200" | "RANGE_200_300" | "RANGE_300_500" | "RANGE_500_1000" | "RANGE_1000_2000" | "RANGE_2000_3000" | "RANGE_3000_5000" | "RANGE_5000_OVER" | "OVER_1_EUK" | "NEGOTIABLE";
                minBudget?: number;
                maxBudget?: number;
                location?: string;
                techNames?: string[];
                sortBy?: string;
            };
            header?: never;
            path: {
                managerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["PageProjectResponse"];
                };
            };
        };
    };
    getFavoriteStatus: {
        parameters: {
            query: {
                userId: number;
            };
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataMapStringObject"];
                };
            };
        };
    };
    getUserFavoriteProjectIds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataListLong"];
                };
            };
        };
    };
}
